export const FETCHING_USER_REGISTER_SUCCESS = "FETCHING_USER_REGISTER_SUCCESS";
export const FETCHING_USER_REGISTER_FAIL = "FETCHING_USER_REGISTER_FAIL"

export function registerAction(registerInfo){
    return { type: FETCHING_USER_REGISTER_FAIL }
}